# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drone.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'drone.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64rone.proto\x12\x05\x64rone\"\x07\n\x05\x45mpty\"Y\n\tTelemetry\x12\x0e\n\x06signal\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\r\n\x05\x61lert\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\r\n\x05ts_ms\x18\x05 \x01(\x03\"\x17\n\x07\x43ommand\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x15\n\x05Reply\x12\x0c\n\x04text\x18\x01 \x01(\t28\n\x06Sensor\x12.\n\x0cGetTelemetry\x12\x0c.drone.Empty\x1a\x10.drone.Telemetry2B\n\x0b\x41ggregation\x12\x33\n\x0fStreamTelemetry\x12\x0c.drone.Empty\x1a\x10.drone.Telemetry0\x01\x32>\n\x08\x41nalysis\x12\x32\n\x0eStreamAnalyzed\x12\x0c.drone.Empty\x1a\x10.drone.Telemetry0\x01\x32g\n\x06Update\x12\x30\n\x0cStreamUpdate\x12\x0c.drone.Empty\x1a\x10.drone.Telemetry0\x01\x12+\n\x0bSendCommand\x12\x0e.drone.Command\x1a\x0c.drone.Reply25\n\x06Server\x12+\n\x0bSendCommand\x12\x0e.drone.Command\x1a\x0c.drone.Replyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drone_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_TELEMETRY']._serialized_start=31
  _globals['_TELEMETRY']._serialized_end=120
  _globals['_COMMAND']._serialized_start=122
  _globals['_COMMAND']._serialized_end=145
  _globals['_REPLY']._serialized_start=147
  _globals['_REPLY']._serialized_end=168
  _globals['_SENSOR']._serialized_start=170
  _globals['_SENSOR']._serialized_end=226
  _globals['_AGGREGATION']._serialized_start=228
  _globals['_AGGREGATION']._serialized_end=294
  _globals['_ANALYSIS']._serialized_start=296
  _globals['_ANALYSIS']._serialized_end=358
  _globals['_UPDATE']._serialized_start=360
  _globals['_UPDATE']._serialized_end=463
  _globals['_SERVER']._serialized_start=465
  _globals['_SERVER']._serialized_end=518
# @@protoc_insertion_point(module_scope)
