# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import drone_pb2 as drone__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in drone_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SensorStub(object):
    """Sensor nodes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTelemetry = channel.unary_unary(
                '/drone.Sensor/GetTelemetry',
                request_serializer=drone__pb2.Empty.SerializeToString,
                response_deserializer=drone__pb2.Telemetry.FromString,
                _registered_method=True)


class SensorServicer(object):
    """Sensor nodes
    """

    def GetTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetry,
                    request_deserializer=drone__pb2.Empty.FromString,
                    response_serializer=drone__pb2.Telemetry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drone.Sensor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drone.Sensor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sensor(object):
    """Sensor nodes
    """

    @staticmethod
    def GetTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drone.Sensor/GetTelemetry',
            drone__pb2.Empty.SerializeToString,
            drone__pb2.Telemetry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AggregationStub(object):
    """Aggregation node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.unary_stream(
                '/drone.Aggregation/StreamTelemetry',
                request_serializer=drone__pb2.Empty.SerializeToString,
                response_deserializer=drone__pb2.Telemetry.FromString,
                _registered_method=True)


class AggregationServicer(object):
    """Aggregation node
    """

    def StreamTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AggregationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=drone__pb2.Empty.FromString,
                    response_serializer=drone__pb2.Telemetry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drone.Aggregation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drone.Aggregation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Aggregation(object):
    """Aggregation node
    """

    @staticmethod
    def StreamTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/drone.Aggregation/StreamTelemetry',
            drone__pb2.Empty.SerializeToString,
            drone__pb2.Telemetry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AnalysisStub(object):
    """Analysis node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAnalyzed = channel.unary_stream(
                '/drone.Analysis/StreamAnalyzed',
                request_serializer=drone__pb2.Empty.SerializeToString,
                response_deserializer=drone__pb2.Telemetry.FromString,
                _registered_method=True)


class AnalysisServicer(object):
    """Analysis node
    """

    def StreamAnalyzed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAnalyzed': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAnalyzed,
                    request_deserializer=drone__pb2.Empty.FromString,
                    response_serializer=drone__pb2.Telemetry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drone.Analysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drone.Analysis', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Analysis(object):
    """Analysis node
    """

    @staticmethod
    def StreamAnalyzed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/drone.Analysis/StreamAnalyzed',
            drone__pb2.Empty.SerializeToString,
            drone__pb2.Telemetry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UpdateStub(object):
    """Update node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamUpdate = channel.unary_stream(
                '/drone.Update/StreamUpdate',
                request_serializer=drone__pb2.Empty.SerializeToString,
                response_deserializer=drone__pb2.Telemetry.FromString,
                _registered_method=True)
        self.SendCommand = channel.unary_unary(
                '/drone.Update/SendCommand',
                request_serializer=drone__pb2.Command.SerializeToString,
                response_deserializer=drone__pb2.Reply.FromString,
                _registered_method=True)


class UpdateServicer(object):
    """Update node
    """

    def StreamUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UpdateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamUpdate': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamUpdate,
                    request_deserializer=drone__pb2.Empty.FromString,
                    response_serializer=drone__pb2.Telemetry.SerializeToString,
            ),
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=drone__pb2.Command.FromString,
                    response_serializer=drone__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drone.Update', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drone.Update', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Update(object):
    """Update node
    """

    @staticmethod
    def StreamUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/drone.Update/StreamUpdate',
            drone__pb2.Empty.SerializeToString,
            drone__pb2.Telemetry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drone.Update/SendCommand',
            drone__pb2.Command.SerializeToString,
            drone__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServerStub(object):
    """Server node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCommand = channel.unary_unary(
                '/drone.Server/SendCommand',
                request_serializer=drone__pb2.Command.SerializeToString,
                response_deserializer=drone__pb2.Reply.FromString,
                _registered_method=True)


class ServerServicer(object):
    """Server node
    """

    def SendCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=drone__pb2.Command.FromString,
                    response_serializer=drone__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drone.Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drone.Server', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Server(object):
    """Server node
    """

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drone.Server/SendCommand',
            drone__pb2.Command.SerializeToString,
            drone__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
