# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import drone_pb2 as drone__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in drone_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AggregationStub(object):
    """////////////////////////////////////////////////////
    Aggregation Service
    Sensors -> Aggregation
    ////////////////////////////////////////////////////

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/drone.Aggregation/Send',
                request_serializer=drone__pb2.DroneData.SerializeToString,
                response_deserializer=drone__pb2.Ack.FromString,
                _registered_method=True)


class AggregationServicer(object):
    """////////////////////////////////////////////////////
    Aggregation Service
    Sensors -> Aggregation
    ////////////////////////////////////////////////////

    """

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AggregationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=drone__pb2.DroneData.FromString,
                    response_serializer=drone__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drone.Aggregation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drone.Aggregation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Aggregation(object):
    """////////////////////////////////////////////////////
    Aggregation Service
    Sensors -> Aggregation
    ////////////////////////////////////////////////////

    """

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drone.Aggregation/Send',
            drone__pb2.DroneData.SerializeToString,
            drone__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AnalysisStub(object):
    """////////////////////////////////////////////////////
    Analysis Service
    Aggregation -> Analysis
    ////////////////////////////////////////////////////

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/drone.Analysis/Analyze',
                request_serializer=drone__pb2.DroneData.SerializeToString,
                response_deserializer=drone__pb2.Ack.FromString,
                _registered_method=True)


class AnalysisServicer(object):
    """////////////////////////////////////////////////////
    Analysis Service
    Aggregation -> Analysis
    ////////////////////////////////////////////////////

    """

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=drone__pb2.DroneData.FromString,
                    response_serializer=drone__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drone.Analysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drone.Analysis', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Analysis(object):
    """////////////////////////////////////////////////////
    Analysis Service
    Aggregation -> Analysis
    ////////////////////////////////////////////////////

    """

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drone.Analysis/Analyze',
            drone__pb2.DroneData.SerializeToString,
            drone__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AlertStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RaiseAlert = channel.unary_unary(
                '/drone.Alert/RaiseAlert',
                request_serializer=drone__pb2.AlertEvent.SerializeToString,
                response_deserializer=drone__pb2.Ack.FromString,
                _registered_method=True)


class AlertServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RaiseAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlertServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RaiseAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.RaiseAlert,
                    request_deserializer=drone__pb2.AlertEvent.FromString,
                    response_serializer=drone__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drone.Alert', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drone.Alert', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Alert(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RaiseAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drone.Alert/RaiseAlert',
            drone__pb2.AlertEvent.SerializeToString,
            drone__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class QueryStub(object):
    """////////////////////////////////////////////////////
    Client Server Service
    ////////////////////////////////////////////////////
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckRunning = channel.unary_unary(
                '/drone.Query/CheckRunning',
                request_serializer=drone__pb2.Empty.SerializeToString,
                response_deserializer=drone__pb2.Ack.FromString,
                _registered_method=True)
        self.SendQuery = channel.unary_unary(
                '/drone.Query/SendQuery',
                request_serializer=drone__pb2.ClientQuery.SerializeToString,
                response_deserializer=drone__pb2.ServerReply.FromString,
                _registered_method=True)


class QueryServicer(object):
    """////////////////////////////////////////////////////
    Client Server Service
    ////////////////////////////////////////////////////
    """

    def CheckRunning(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckRunning': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckRunning,
                    request_deserializer=drone__pb2.Empty.FromString,
                    response_serializer=drone__pb2.Ack.SerializeToString,
            ),
            'SendQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.SendQuery,
                    request_deserializer=drone__pb2.ClientQuery.FromString,
                    response_serializer=drone__pb2.ServerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drone.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drone.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """////////////////////////////////////////////////////
    Client Server Service
    ////////////////////////////////////////////////////
    """

    @staticmethod
    def CheckRunning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drone.Query/CheckRunning',
            drone__pb2.Empty.SerializeToString,
            drone__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drone.Query/SendQuery',
            drone__pb2.ClientQuery.SerializeToString,
            drone__pb2.ServerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
