# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drone.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'drone.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64rone.proto\x12\x05\x64rone\"K\n\tDroneData\x12\x0c\n\x04node\x18\x01 \x01(\t\x12\x0e\n\x06signal\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\"E\n\nAlertEvent\x12\x13\n\x0bsource_node\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32\x33\n\x0b\x41ggregation\x12$\n\x04Send\x12\x10.drone.DroneData\x1a\n.drone.Ack23\n\x08\x41nalysis\x12\'\n\x07\x41nalyze\x12\x10.drone.DroneData\x1a\n.drone.Ack24\n\x05\x41lert\x12+\n\nRaiseAlert\x12\x11.drone.AlertEvent\x1a\n.drone.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drone_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRONEDATA']._serialized_start=22
  _globals['_DRONEDATA']._serialized_end=97
  _globals['_ACK']._serialized_start=99
  _globals['_ACK']._serialized_end=116
  _globals['_ALERTEVENT']._serialized_start=118
  _globals['_ALERTEVENT']._serialized_end=187
  _globals['_AGGREGATION']._serialized_start=189
  _globals['_AGGREGATION']._serialized_end=240
  _globals['_ANALYSIS']._serialized_start=242
  _globals['_ANALYSIS']._serialized_end=293
  _globals['_ALERT']._serialized_start=295
  _globals['_ALERT']._serialized_end=347
# @@protoc_insertion_point(module_scope)
