# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drone.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'drone.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64rone.proto\x12\x05\x64rone\"K\n\tDroneData\x12\x0c\n\x04node\x18\x01 \x01(\t\x12\x0e\n\x06signal\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"!\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"E\n\nAlertEvent\x12\x13\n\x0bsource_node\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x1e\n\x0b\x43lientQuery\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x1c\n\x0bServerReply\x12\r\n\x05reply\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2`\n\x0b\x41ggregation\x12$\n\x04Send\x12\x10.drone.DroneData\x1a\n.drone.Ack\x12+\n\rGetSensorData\x12\x0c.drone.Empty\x1a\n.drone.Ack0\x01\x32\x33\n\x06Sensor\x12)\n\x07GetData\x12\x0c.drone.Empty\x1a\x10.drone.DroneData23\n\x08\x41nalysis\x12\'\n\x07\x41nalyze\x12\x10.drone.DroneData\x1a\n.drone.Ack24\n\x05\x41lert\x12+\n\nRaiseAlert\x12\x11.drone.AlertEvent\x1a\n.drone.Ack2h\n\x05Query\x12(\n\x0c\x43heckRunning\x12\x0c.drone.Empty\x1a\n.drone.Ack\x12\x35\n\tSendQuery\x12\x12.drone.ClientQuery\x1a\x12.drone.ServerReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drone_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRONEDATA']._serialized_start=22
  _globals['_DRONEDATA']._serialized_end=97
  _globals['_ACK']._serialized_start=99
  _globals['_ACK']._serialized_end=132
  _globals['_ALERTEVENT']._serialized_start=134
  _globals['_ALERTEVENT']._serialized_end=203
  _globals['_CLIENTQUERY']._serialized_start=205
  _globals['_CLIENTQUERY']._serialized_end=235
  _globals['_SERVERREPLY']._serialized_start=237
  _globals['_SERVERREPLY']._serialized_end=265
  _globals['_EMPTY']._serialized_start=267
  _globals['_EMPTY']._serialized_end=274
  _globals['_AGGREGATION']._serialized_start=276
  _globals['_AGGREGATION']._serialized_end=372
  _globals['_SENSOR']._serialized_start=374
  _globals['_SENSOR']._serialized_end=425
  _globals['_ANALYSIS']._serialized_start=427
  _globals['_ANALYSIS']._serialized_end=478
  _globals['_ALERT']._serialized_start=480
  _globals['_ALERT']._serialized_end=532
  _globals['_QUERY']._serialized_start=534
  _globals['_QUERY']._serialized_end=638
# @@protoc_insertion_point(module_scope)
